### ISSUE TITLE
Live reload doesn't work after the first reload

### ISSUE THREAD

**Issue by rhyses-pieces** [nijikokun/sugarcube-starter#2]
Hello! I'm trying out this starter, but I noticed that the Live Reloading feature only works on the first rebuild, and not on subsequent rebuilds. I tried using the "--watch" option in the config file like this: 

```
"tweego": {
  "dir": "./.tweego",
  "options": ["--watch"],
  …
}
```

… but the terminal stays stuck at this message when it's building the index.html file: 

```
[builder] [init] Running build.

Watch mode started.  Press CTRL+C to stop.

Recursively watched paths: 3
  src\story
  dist\scripts
  dist\styles

BUILDING: dist\index.html
```

Is there any way to get both the Tweego rebuilding and style/js rebuilding processes to work at the same time?

**Comment by nijikokun** [comment]
I'd have to know what issues would be occurring that are preventing it from reloading.

**Comment by nijikokun** [comment]
This has been fixed in the latest release!
