### ISSUE TITLE
Wrong version of tweego is pulled for macOS ARM platforms

### ISSUE THREAD

**Issue by midona-rhel** [nijikokun/sugarcube-starter#8]
Hi, 

Decided to give this a spin and mess around with it a bit, got some spawnsync errors that it wouldn't run tweego however so decided to try to see if I can fix it. I am not sure which version gets downloaded really but whichever one it is it is the wrong version for macOS arm computers. The one that should be pulled is the [tweego-2.1.1-macos-x64.zip (64-bit)](https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-macos-x64.zip) version of tweego. I fixed it myself locally by just replacing the file but I thought I should at least give a headsup since twine and typescript seems like a great idea and I am very happy this project exists!

**Comment by nijikokun** [comment]
It looks like `process.arch` returns `arm64` when it's ARM, I have updated the `config.json` to include a key for `arm64` which should solve this issue. Do you mind testing and letting me know if it works?

**Comment by midona-rhel** [comment]
It works, thank you for taking time to fix this!
